folders:
  # Where the raw data is kept
  raw-folder:
  # Where the STAC data might go
  processed-folder:
  # For analysis mostly
  data-folder:

logging:
  # The logging level
  # Possible values are "NOTSET", "DEBUG", "INFO", "WARNING" and "ERROR"
  level: "NOTSET"

catalog:
  id: "lno-10-days"
  catalog_descr: "a descr"
  bands:
    - "lno"
